//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeQuiz.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Quiz
    {
        public int Score { get; set; }
        public int TaskCount { get; set; }
        public int ImageCount { get; set; }
        public IEnumerable<Task> Tasks { get; set; }
        public Task CurrentTask { get; set; }
        public ImageSet CurrentImageset { get; set; }
        public string Finish;
        public bool NewHigh { get; set; }
        public ScoreBoard ScoreEntry { get; set; }
        public IEnumerable<ScoreBoard> LeaderBoard { get; set; }
        public int RemainingMinutes { get; set; }
        public int RemainingSecounds { get; set; }


    }
}
